# JavaScript 异步编程模式

# Promise 编排

## Promise 编排

```js
/*
 * promiseSerial resolves Promises sequentially.
 * @example
 * const urls = ['/url1', '/url2', '/url3']
 * const funcs = urls.map(url => () => $.ajax(url))
 *
 * promiseSerial(funcs)
 *   .then(console.log)
 *   .catch(console.error)
 */
const promiseSerial = funcs =>
  funcs.reduce(
    (promise, func) =>
      promise.then(result => func().then(Array.prototype.concat.bind(result))),
    Promise.resolve([])
  );

// some url's to resolve
const urls = ['/url1', '/url2', '/url3'];

// convert each url to a function that returns a promise
const funcs = urls.map(url => () => $.ajax(url));

// execute Promises in serial
promiseSerial(funcs)
  .then(console.log)
  .catch(console.error);
```

### Promise.race: 返回第一个确定状态

race 函数返回一个 Promise，这个 Promise 根据传入的 Promise 中的第一个确定状态 -- 不管是接受还是拒绝 -- 的状态而确定状态。

```js
var p1 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 500, '一');
});
var p2 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 100, '二');
});

Promise.race([p1, p2]).then(function(value) {
  console.log(value); // "二"
  // 两个都解决，但p2更快
});

var p3 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 100, '三');
});
var p4 = new Promise(function(resolve, reject) {
  setTimeout(reject, 500, '四');
});

Promise.race([p3, p4]).then(
  function(value) {
    console.log(value); // "三"
    // p3更快，所以被解决（resolve）了
  },
  function(reason) {
    // 未被执行
  }
);

var p5 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 500, '五');
});
var p6 = new Promise(function(resolve, reject) {
  setTimeout(reject, 100, '六');
});

Promise.race([p5, p6]).then(
  function(value) {
    // 未被执行
  },
  function(reason) {
    console.log(reason); // "六"
    // p6更快，所以被拒绝（reject了）
  }
);
```

```js
function executeAsyncTask() {
  return functionA().then(valueA => {
    return functionB(valueA).then(valueB => {
      return functionC(valueA, valueB);
    });
  });
}
```

```js
const converge = (...promises) => (...args) => {
  let [head, ...tail] = promises;
  if (tail.length) {
    return head(...args).then(value =>
      converge(...tail)(...args.concat([value]))
    );
  } else {
    return head(...args);
  }
};

functionA(2).then(valueA => converge(functionB, functionC)(valueA));
```

```
let promise = new Promise((resolve,reject)=>{
	setTimeout(()=>{
		console.log('2 in setTimeout');
		resolve(2);
	},0);
	resolve(1);
});


promise.then((value)=>{
	console.log(value);
})


// 1
// 2 in setTimeout
```

```js
const prom = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(5);
  }, 1000);
});

prom.then(value => {
  console.log(value);
});

setTimeout(() => {
  prom.then(value => {
    console.log(value);
  });
}, 5000);
```

## Promise.all: 并发执行

async/await 默认情况下是顺序执行的，

```js
async function executeAsyncTask() {
  const valueA = await functionA();
  const valueB = await functionB(valueA);
  return function3(valueA, valueB);
}
```

```js
async function executeParallelAsyncTasks() {
  const [valueA, valueB, valueC] = await Promise.all([
    functionA(),
    functionB(),
    functionC()
  ]);
  doSomethingWith(valueA);
  doSomethingElseWith(valueB);
  doAnotherThingWith(valueC);
}
```

# 异常处理

最容易犯的错误，没有使用 `catch` 去捕获 `then` 里抛出的报错：

```js
// snippet1
somePromise()
  .then(function() {
    throw new Error('oh noes');
  })
  .catch(function(err) {
    // I caught your error! :)
  });

// snippet2
somePromise().then(
  function resolve() {
    throw new Error('oh noes');
  },
  function reject(err) {
    // I didn't catch your error! :(
  }
);
```

这里的问题在于 snippet2 在 function resolve 中出错时无法捕获。而 catch 则可以。

下面的两个示例返回结果是不一样的：

```js
// example1
Promise.resolve('foo')
  .then(Promise.resolve('bar'))
  .then(function(result) {
    console.log(result); // foo
  });
// example2
Promise.resolve('foo')
  .then(function() {
    return Promise.resolve('bar');
  })
  .then(function(result) {
    console.log(result); // bar
  });
```

example2 改变了返回值，因而 result 发生了变化。

引入[此文](https://blog.lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795)中对于 async/await 的循环的写法

```js
async function waitAndMaybeReject() {
  // Wait one second
  await new Promise(r => setTimeout(r, 1000));
  // Toss a coin
  const isHeads = Boolean(Math.round(Math.random()));

  if (isHeads) return 'yay';
  throw Error('Boo!');
}

async function foo() {
  try {
    // Wait for the result of waitAndMaybeReject() to settle,
    // and assign the fulfilled value to fulfilledValue:
    const fulfilledValue = await waitAndMaybeReject();
    // If the result of waitAndMaybeReject() rejects, our code
    // throws, and we jump to the catch block.
    // Otherwise, this block continues to run:
    return fulfilledValue;
  } catch (e) {
    return 'caught';
  }
}
```

Promises 是为了让异步代码也能保持这些同步代码的属性：扁平缩进和单异常管道。在 ES6 之前，存在着很多的 Promise 的支持库，譬如著名的 q 以及 jQuery 中都有着对于 Promise 模式的内在的实现。在 ES6 之后，笔者是推荐仅使用 ES6 提供的 Promise 对象。

# 避免异步混淆与性能损耗

async/await 允许我们以同步的方式编写异步代码，不过这种方式也可能带来额外的性能损耗，或者混淆现有的代码逻辑。

```js
(async () => {
  const pizzaData = await getPizzaData(); // async call
  const drinkData = await getDrinkData(); // async call
  const chosenPizza = choosePizza(); // sync call
  const chosenDrink = chooseDrink(); // sync call
  await addPizzaToCart(chosenPizza); // async call
  await addDrinkToCart(chosenDrink); // async call
  orderItems(); // async call
})();
```

所有这些语句一个接一个地执行。这里没有并行逻辑。细想一下：为什么我们要在获取饮料列表之前等待获取披萨列表？我们应该尝试一起获取这两个列表。然而，当我们需要选择一个披萨的时候，我们确实需要在这之前获取披萨列表。对于饮料来说，道理类似。因此，我们可以总结如下：披萨相关的任务和饮料相关的任务可以并行发生，但是披萨（或饮料）各自的相关步骤需要按顺序（一个接一个地）发生。

```js
async function orderItems() {
  const items = await getCartItems(); // async call
  const noOfItems = items.length;
  for (var i = 0; i < noOfItems; i++) {
    await sendRequest(items[i]); // async call
  }
}
```

找出那些依赖其它语句执行的语句，将相互依赖的语句包在一个 async 函数中，然后并行执行这些 async 函数。可以利用事件循环来并行运行这些异步非阻塞函数。这样做的两种常见模式是 先返回 promise 和 Promise.all 方法。

```js
async function selectPizza() {
  const pizzaData = await getPizzaData(); // async call
  const chosenPizza = choosePizza(); // sync call
  await addPizzaToCart(chosenPizza); // async call
}

async function selectDrink() {
  const drinkData = await getDrinkData(); // async call
  const chosenDrink = chooseDrink(); // sync call
  await addDrinkToCart(chosenDrink); // async call
}

(async () => {
  const pizzaPromise = selectPizza();
  const drinkPromise = selectDrink();
  await pizzaPromise;
  await drinkPromise;
  orderItems(); // async call
})()(
  // Although I prefer it this way

  async () => {
    Promise.all([selectPizza(), selectDrink()]).then(orderItems); // async call
  }
)();
```

在第二个例子中，我们需要处理不确定数量的 promise。处理这种情况超级简单：我们只用创建一个数组，然后将所有的 promise 放进数组中。然后使用 Promise.all()，我们就可以并行等待所有的 promise 处理。

```js
async function orderItems() {
  const items = await getCartItems(); // async call
  const noOfItems = items.length;
  const promises = [];
  for (var i = 0; i < noOfItems; i++) {
    const orderPromise = sendRequest(items[i]); // async call
    promises.push(orderPromise); // sync call
  }
  await Promise.all(promises); // async call
}
```
